# .upptimerc.yml
owner: OwenICT
repo: uptime-monitor
sites:
  - name: OwenICT hoofddomein
    url: https://owenict.nl
  - name: DirectAdmin panel
    url: https://wing-of-hoatzin.vertexzone.nl:222
status-website:
  cname: status.owenict.nl
  name: OwenICT Status
  theme: dark
  logoUrl: https://owenict.nl/wp-content/uploads/2025/08/Logo_Primair_Compleet_Horizontaal_Owen_ICT_2000px_RGB_PNG-1.png
commitMessages:
  status: "📈 status update"
  summary: "📝 update summary"
  readme: "📄 update readme"
  graphs: "📊 update graphs"
timezone: Europe/Amsterdam
assignees: []
issueTemplates:
  outage: "🚨 {NAME} is down"
  degraded: "⚠️ {NAME} is experiencing issues"
