owner: OwenICT
repo: uptime-monitor

sites:
  - name: Zeta-monitor
    url: https://zeta.owenict.nl
  - name: DirectAdmin
    url: https://wing-of-hoatzin.vertexzone.nl:2222

status-website:
  name: OwenICT Status
  theme: light
  logoUrl: https://owenict.nl/wp-content/uploads/2025/08/Logo_Primair_Compleet_Horizontaal_Owen_ICT_2000px_RGB_PNG-1.png

commitMessages:
  status: "📈 status update"
  summary: "📝 update summary"
  readme: "📄 update readme"
  graphs: "📊 update graphs"

timezone: Europe/Amsterdam
assignees: []

issueTemplates:
  outage: "🚨 {NAME} is down"
  degraded: "⚠️ {NAME} is experiencing issues"
